spring.application.name=bootCompanny
spring.datasource.url=jdbc:mysql://localhost:3306/company_db
spring.datasource.username=root
spring.datasource.password=Kanha123
server.port=8081
logger.level.org.hibernate.SQL= DEBUG
#logging.level.root = DEBUG
logging.level.org.springframework = DEBUG