spring.application.name=mockito_training
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/mockito_training_db
spring.datasource.username=root
spring.datasource.password=Kanha123


spring.jpa.generate-ddl=true







